name: Bug Report
description: Something is broken? File a bug report!
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before reporting an issue, please search through [issues](https://github.com/etournity/etournity/labels/bug) to see if someone already reported this or a similar bug.
        Feel free to comment on that issue instead!
  - type: dropdown
    id: type
    attributes:
      options:
        - Visual
        - Content
        - Functionality
        - Performance
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Tell us what happened. If possible, please also include what you did before you encountered the issue. What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots-video
    attributes:
      label: Screenshots or videos
      description: Please add any screenshots or video of the issue by either copy & pasting or dragging & dropping into the field below.
    validadtions:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - OperaGX
        - Safari
        - Microsoft Edge
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
      id: contact
      attributes:
        label: Contact Details (optional)
        description: How can we get in touch with you if we need more info?
        placeholder: ex. email@example.com / discordname#0000
      validations:
        required: false
