blank_issues_enabled: true
contact_links:
  - name: Ideas / Feature Requests
    url: https://github.com/etournity/etournity/discussions/categories/ideas
    about: Let us know if we are missing feature or propose ideas for the future of the project.
  - name: Discord
    url: https://discord.com/invite/ysm29w7Yxn
    about: Get in touch with the team and other community members.
