name: Production Backend Deploy

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: etournity-prod-ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f scripts/server.Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          DOCKER_HUB_REPOSITORY: docker-hub-repo
          IMAGE_TAG: ${{ github.sha }}
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t $USERNAME/$DOCKER_HUB_REPOSITORY:$IMAGE_TAG -t $USERNAME/$DOCKER_HUB_REPOSITORY:prod -f scripts/server.Dockerfile .
          docker push $USERNAME/$DOCKER_HUB_REPOSITORY --all-tags
          echo "::set-output name=image::$DOCKER_HUB_REPOSITORY:$IMAGE_TAG"

